import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'hi' | 'mr' | 'gu' | 'ta' | 'te' | 'es';

export interface LanguageOption {
  code: LanguageCode;
  name: string; // Native name
  englishName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', englishName: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'हिन्दी', englishName: 'Hindi', flag: '🇮🇳' },
  { code: 'mr', name: 'मराठी', englishName: 'Marathi', flag: '🇮🇳' },
  { code: 'gu', name: 'ગુજરાતી', englishName: 'Gujarati', flag: '🇮🇳' },
  { code: 'ta', name: 'தமிழ்', englishName: 'Tamil', flag: '🇮🇳' },
  { code: 'te', name: 'తెలుగు', englishName: 'Telugu', flag: '🇮🇳' },
  { code: 'es', name: 'Español', englishName: 'Spanish', flag: '🇪🇸' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navigation & Sidebar
    'nav.coreModules': 'Core Modules',
    'nav.dashboard': 'Dashboard',
    'nav.employees': 'Employees',
    'nav.supportDesk': 'Live Support Desk',
    'nav.requests': 'Requests & Approvals',
    'nav.attendance': 'Attendance & Leave',
    'nav.payroll': 'Payroll & Compensation',
    'nav.organization': 'Organization',
    'nav.usersRoles': 'User & Roles',
    'nav.auditLogs': 'Audit & Compliance',
    'nav.more': 'More',
    'sidebar.dbConnected': 'Isolated DB Connected',

    // Header & Profile Popover
    'header.searchPlaceholder': 'Search directory, requests, records...',
    'header.companyName': 'Priyex Software Enterprise',
    'header.supportPool': 'Pool',
    'header.notifications': 'Notifications',
    'header.myProfile': 'My Profile',
    'header.systemRole': 'System Role',
    'header.accountId': 'Account ID',
    'header.sessionStatus': 'Session Status',
    'header.activeOnline': 'Active Online',
    'header.signOut': 'Sign Out Session',
    'header.theme': 'Theme Color',
    'header.language': 'Language',

    // Dashboard Banner & Headings
    'dash.welcomeBack': 'Welcome back',
    'dash.enterprisePortal': 'Enterprise HR & Workforce Portal',
    'dash.q3Overview': 'Enterprise HR Overview',
    'dash.adminSubtitle': 'Real-time overview of workforce operations, attendance health, and payroll across all branch locations.',
    'dash.empSubtitle': 'Access your employee profile, attendance calendar, shift schedules, and apply for leave applications.',
    'dash.applyLeave': 'Apply for Leave',
    'dash.viewPayslips': 'View Payslips',
    'dash.addEmployee': 'Add Employee',
    'dash.downloadReport': 'Download Summary',
    'dash.quickActions': 'Quick Actions',
    'dash.liveActivity': 'Live System Activity',
    'dash.recentActivity': 'My Recent Activity & Timeline',
    'dash.viewAll': 'View All',

    // Activity Items
    'dash.act.onboarded': 'Employee Onboarded',
    'dash.act.onboardedDesc': 'Rajesh Kumar joined as Lead Frontend Engineer',
    'dash.act.time10m': '10 mins ago',
    'dash.act.leaveApproved': 'Leave Approved',
    'dash.act.leaveApprovedDesc': 'Priya Sharma - Annual Leave (3 Days)',
    'dash.act.time25m': '25 mins ago',
    'dash.act.payrollRun': 'Payroll Run',
    'dash.act.payrollRunDesc': 'Monthly Payroll Draft generated for active employees',
    'dash.act.time1h': '1 hour ago',
    'dash.act.attendanceAlert': 'Attendance Alert',
    'dash.act.attendanceAlertDesc': 'Missed punchouts flagged for verification',
    'dash.act.time2h': '2 hours ago',
    'dash.act.leaveRequest': 'Leave Request',
    'dash.act.leaveRequestDesc': 'Leave request submitted — Pending Manager Approval',
    'dash.act.today': 'Today',
    'dash.act.attendanceRecorded': 'Attendance Recorded',
    'dash.act.attendanceRecordedDesc': 'Biometric punch-in recorded today — On time',
    'dash.act.payslipReleased': 'Payslip Released',
    'dash.act.payslipReleasedDesc': 'Monthly Salary Statement generated & ready for download',
    'dash.act.yesterday': 'Yesterday',
    'dash.act.hrSupport': 'HR Support',
    'dash.act.hrSupportDesc': 'PF & UAN query responded by HR Specialist',
    'dash.act.time2d': '2 days ago',

    // KPI Cards
    'dash.kpi.daysPresent': 'Days Present',
    'dash.kpi.leaveBalance': 'Leave Balance',
    'dash.kpi.latestNetPay': 'Latest Net Pay',
    'dash.kpi.activeRequests': 'Active Requests',
    'dash.kpi.totalStaff': 'Total Staff',
    'dash.kpi.presentToday': 'Present Today',
    'dash.kpi.staffOnLeave': 'Staff On Leave',
    'dash.kpi.monthlyPayroll': 'Monthly Payroll',
    'dash.kpi.onTime': 'on-time attendance',
    'dash.kpi.daysAvailable': 'Days Available',
    'dash.kpi.inReview': 'In Review',
    'dash.kpi.availableLeaves': 'annual leaves remaining',
    'dash.kpi.credited': 'Credited on Aug 31',
    'dash.kpi.awaitingApproval': 'Casual leave awaiting approval',
    'dash.kpi.daysUnit': '/ 22 Days',
    'dash.kpi.perMonth': '/ month',
    'dash.kpi.activeStaff': 'Active Staff',
    'dash.kpi.staffTrend': 'of directory active',
    'dash.kpi.staffRatio': 'Staff',
    'dash.kpi.dailyAttendance': 'daily attendance',
    'dash.kpi.planned': 'Planned',
    'dash.kpi.leaveRate': 'daily leave rate',
    'dash.kpi.gross': 'Gross',
    'dash.kpi.payrollTrend': '+4.2% disbursement run',

    // Hub & Company Scope
    'dash.companyScope': 'Company Scope',
    'dash.primaryEntity': 'Primary Entity',
    'dash.activeBranches': 'Active Branches',
    'dash.databaseSchema': 'Database Schema',
    'dash.flywayMigrations': 'Flyway Migrations',
    'dash.quickHub': 'Quick Self-Service Hub',
    'dash.applyLeaveDesc': 'Submit paid time off or casual leave',
    'dash.viewPayslipsDesc': 'Download monthly salary breakdown & tax',
    'dash.profileRequests': 'Profile Update Requests',
    'dash.profileRequestsDesc': 'Request address, phone or bank updates',
    'dash.portalAccountId': 'Portal Account ID:',
    'dash.verificationStatus': 'Verification Status:',
    'dash.biometricLinked': 'Active • Biometric Linked',

    // Requests Page
    'req.headerTitle': 'HR Operations & Request Desk',
    'req.headerSubtitle': 'Review employee profile update approvals and respond to employee HR inquiries.',
    'req.tabRequests': 'Profile Change Requests',
    'req.tabQueries': 'HR Helpdesk & Queries',
    'req.filterStatus': 'Status:',
    'req.queryStatus': 'Query Status:',
    'status.all': 'ALL',
    'status.pending': 'PENDING',
    'status.approved': 'APPROVED',
    'status.rejected': 'REJECTED',
    'status.open': 'OPEN',
    'status.inProgress': 'IN PROGRESS',
    'status.resolved': 'RESOLVED',
    'status.closed': 'CLOSED',
    'req.thEmployee': 'Employee',
    'req.thChange': 'Requested Change',
    'req.thCurrentVsRequested': 'Current vs Requested',
    'req.thStatus': 'Status',
    'req.thSubmittedAt': 'Submitted At',
    'req.thAction': 'Review Action',
    'req.newRequest': 'New Change Request',
    'req.thEmpCode': 'Employee & Code',
    'req.thSubjectCat': 'Subject & Category',
    'req.thAssignedHr': 'Assigned HR',
    'req.thPriority': 'Priority',
    'req.actions': 'Actions',
    'req.reason': 'Reason:',
    'btn.approve': 'Approve',
    'btn.reject': 'Reject',
    'req.reviewedBy': 'Reviewed by',
    'req.loadingRequests': 'Loading requests...',
    'req.noRequests': 'No profile change requests found.',
    'req.loadingQueries': 'Loading queries...',
    'req.noQueries': 'No HR inquiries found.',
    'req.approveReq': 'Approve Change Request',
    'req.rejectReq': 'Reject Change Request',
    'req.reviewerNotes': 'Reviewer Notes (Optional)',
    'req.confirmApprove': 'Confirm Approval',
    'req.confirmReject': 'Confirm Rejection',
    'req.submitChangeReq': 'Submit Profile Change Request',
    'req.changeType': 'Change Type',
    'req.newRequestedVal': 'New Requested Value',
    'req.reasonNote': 'Reason / Supporting Note',
    'req.submitToHr': 'Submit to HR Manager',
    'req.hrQueryResponse': 'HR Query & Response',
    'req.hrReplyDetails': 'HR Reply & Resolution Details',
    'req.updateStatusTo': 'Update Status to',
    'req.sendResolution': 'Send Resolution to Employee',
    'field.BANK_ACCOUNT': 'Bank Account & IFSC',
    'field.CONTACT_NAME': 'Legal Full Name',
    'field.EMAIL': 'Official Email',
    'field.OTHER': 'Other Official Record',
    'field.Bank Account Number': 'Bank Account Number',
    'field.Legal Full Name': 'Legal Full Name',
    'field.Personal Email': 'Personal Email',
    'field.Phone Number': 'Phone Number',
    'field.Residential Address': 'Residential Address',

    // Modal
    'modal.onboardEmployee': 'Onboard New Employee',
    'modal.firstName': 'First Name',
    'modal.lastName': 'Last Name',
    'modal.workEmail': 'Work Email',
    'modal.phone': 'Phone Number',
    'modal.department': 'Department',
    'modal.selectDept': 'Select Department',
    'modal.employmentType': 'Employment Type',
    'modal.fullTime': 'Full Time',
    'modal.partTime': 'Part Time',
    'modal.contract': 'Contract',
    'modal.joiningDate': 'Joining Date',
    'modal.cancel': 'Cancel',
    'modal.saveOnboard': 'Save & Onboard Employee',

    // Live Helpdesk Chat
    'chat.liveHelpdesk': 'Live HR Helpdesk',
    'chat.online': 'Online',
    'chat.instantAssist': 'Instant Employee Assistance',
    'chat.connectedWith': 'Connected with HR Specialist',
    'chat.startSupportChat': 'Start Live Support Chat',
    'chat.describeQuery': 'Describe your HR query or question...',
    'chat.category': 'Category',
    'chat.generalQuery': 'General Query',
    'chat.payrollComp': 'Payroll & Compensation',
    'chat.leaveTimeOff': 'Leaves & Time-off',
    'chat.pfBenefits': 'PF & Benefits',
    'chat.profileDocs': 'Profile / Documents',
    'chat.startSession': 'Start Chat Session',
    'chat.connecting': 'Connecting you to an available HR specialist...',
    'chat.send': 'Send',
    'chat.typeMessage': 'Type message to HR specialist...',
    'chat.waitingInPool': 'Waiting in Available Pool...',
    'chat.resolveClose': 'Resolve & Close',
    'chat.waitingForHr': 'Waiting for HR Specialist...',
    'chat.queueNotice': 'Your query has entered the live support queue. An active HR admin will pick up your chat in a few moments.',
    'chat.employee': 'Employee',
    'chat.addDetailsPlaceholder': 'Add more details while waiting...',
    'chat.briefSubject': 'Brief Subject',
    'chat.subjectPlaceholder': 'e.g., Question about my September payslip deduction',
    'chat.describeQueryLabel': 'Describe your query',
    'chat.describePlaceholder': 'Type details so the HR representative can assist you...',
    'chat.connectingPool': 'Connecting to HR Pool...',
    'chat.sendToAvailableHr': 'Send Request to Available HR',
  },

  hi: {
    // Navigation & Sidebar
    'nav.coreModules': 'मुख्य मॉड्यूल',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.employees': 'कर्मचारी सूची',
    'nav.supportDesk': 'लाइव सहायता डेस्क',
    'nav.requests': 'अनुरोध और अनुमोदन',
    'nav.attendance': 'उपस्थिति और अवकाश',
    'nav.payroll': 'वेतन और मुआवजा',
    'nav.organization': 'संगठन संरचना',
    'nav.usersRoles': 'उपयोगकर्ता और भूमिकाएं',
    'nav.auditLogs': 'ऑडिट और अनुपालन',
    'nav.more': 'अधिक',
    'sidebar.dbConnected': 'पृथक डेटाबेस कनेक्टेड',

    // Header & Profile Popover
    'header.searchPlaceholder': 'निर्देशिका, अनुरोध, रिकॉर्ड खोजें...',
    'header.companyName': 'प्रियैक्स सॉफ्टवेयर एंटरप्राइज',
    'header.supportPool': 'सहायता पूल',
    'header.notifications': 'सूचनाएं',
    'header.myProfile': 'मेरी प्रोफाइल',
    'header.systemRole': 'सिस्टम भूमिका',
    'header.accountId': 'खाता आईडी',
    'header.sessionStatus': 'सत्र स्थिति',
    'header.activeOnline': 'सक्रिय ऑनलाइन',
    'header.signOut': 'सत्र समाप्त करें (लॉग आउट)',
    'header.theme': 'थीम रंग',
    'header.language': 'भाषा चुनें',

    // Dashboard Banner & Headings
    'dash.welcomeBack': 'स्वागत है',
    'dash.enterprisePortal': 'एंटरप्राइज एचआर और कार्यबल पोर्टल',
    'dash.q3Overview': 'Q3 2026 एंटरप्राइज अवलोकन',
    'dash.adminSubtitle': 'सभी सिस्टम सामान्य हैं। मल्टी-टेनेंट कंपनी अलगाव के साथ पोस्टग्रेएसक्यूएल डेटाबेस सक्रिय है।',
    'dash.empSubtitle': 'अपनी कर्मचारी प्रोफ़ाइल, उपस्थिति कैलेंडर देखें और अवकाश के लिए आवेदन करें।',
    'dash.applyLeave': 'अवकाश के लिए आवेदन करें',
    'dash.viewPayslips': 'वेतन पर्ची देखें',
    'dash.addEmployee': 'नया कर्मचारी जोड़ें',
    'dash.downloadReport': 'रिपोर्ट डाउनलोड करें',
    'dash.quickActions': 'त्वरित कार्रवाई',
    'dash.liveActivity': 'लाइव सिस्टम गतिविधि',
    'dash.recentActivity': 'मेरी हाल की गतिविधि और समयरेखा',
    'dash.viewAll': 'सभी देखें',

    // Activity Items
    'dash.act.onboarded': 'कर्मचारी ऑनबोर्ड किया गया',
    'dash.act.onboardedDesc': 'राजेश कुमार लीड फ्रंटएंड इंजीनियर के रूप में शामिल हुए',
    'dash.act.time10m': '10 मिनट पहले',
    'dash.act.leaveApproved': 'अवकाश स्वीकृत',
    'dash.act.leaveApprovedDesc': 'प्रिया शर्मा - वार्षिक अवकाश (3 दिन)',
    'dash.act.time25m': '25 मिनट पहले',
    'dash.act.payrollRun': 'पेरोल प्रक्रिया',
    'dash.act.payrollRunDesc': 'सक्रिय कर्मचारियों के लिए पेरोल ड्राफ्ट तैयार',
    'dash.act.time1h': '1 घंटा पहले',
    'dash.act.attendanceAlert': 'उपस्थिति चेतावनी',
    'dash.act.attendanceAlertDesc': 'सत्यापन के लिए मिस्ड पंचआउट चिह्नित',
    'dash.act.time2h': '2 घंटे पहले',
    'dash.act.leaveRequest': 'अवकाश अनुरोध',
    'dash.act.leaveRequestDesc': 'अवकाश अनुरोध प्रस्तुत — प्रबंधक अनुमोदन की प्रतीक्षा में',
    'dash.act.today': 'आज',
    'dash.act.attendanceRecorded': 'उपस्थिति दर्ज',
    'dash.act.attendanceRecordedDesc': 'बायोमेट्रिक पंच-इन — समय पर',
    'dash.act.payslipReleased': 'वेतन पर्ची जारी',
    'dash.act.payslipReleasedDesc': 'वेतन विवरण तैयार और डाउनलोड के लिए उपलब्ध',
    'dash.act.yesterday': 'कल',
    'dash.act.hrSupport': 'एचआर सहायता',
    'dash.act.hrSupportDesc': 'पीएफ और यूएएन प्रश्न का एचआर विशेषज्ञ द्वारा उत्तर दिया गया',
    'dash.act.time2d': '2 दिन पहले',

    // KPI Cards
    'dash.kpi.daysPresent': 'उपस्थित दिन',
    'dash.kpi.leaveBalance': 'अवकाश शेष',
    'dash.kpi.latestNetPay': 'नवीनतम शुद्ध वेतन',
    'dash.kpi.activeRequests': 'सक्रिय अनुरोध',
    'dash.kpi.totalStaff': 'कुल कर्मचारी',
    'dash.kpi.presentToday': 'आज उपस्थित',
    'dash.kpi.staffOnLeave': 'अवकाश पर कर्मचारी',
    'dash.kpi.monthlyPayroll': 'मासिक पेरोल',
    'dash.kpi.onTime': 'समय पर उपस्थिति',
    'dash.kpi.daysAvailable': 'दिन उपलब्ध',
    'dash.kpi.inReview': 'समीक्षाधीन',
    'dash.kpi.availableLeaves': 'वार्षिक अवकाश शेष',
    'dash.kpi.credited': 'जमा किया गया',
    'dash.kpi.awaitingApproval': 'आकस्मिक अवकाश अनुमोदन की प्रतीक्षा में',
    'dash.kpi.daysUnit': '/ 22 दिन',
    'dash.kpi.perMonth': '/ माह',
    'dash.kpi.activeStaff': 'सक्रिय कर्मचारी',
    'dash.kpi.staffTrend': 'सक्रिय कर्मचारी अनुपात',
    'dash.kpi.staffRatio': 'कर्मचारी',
    'dash.kpi.dailyAttendance': 'दैनिक उपस्थिति',
    'dash.kpi.planned': 'नियोजित',
    'dash.kpi.leaveRate': 'दैनिक अवकाश दर',
    'dash.kpi.gross': 'सकल',
    'dash.kpi.payrollTrend': '+4.2% संवितरण रन',

    // Hub & Company Scope
    'dash.companyScope': 'कंपनी दायरा',
    'dash.primaryEntity': 'मुख्य संस्था',
    'dash.activeBranches': 'सक्रिय शाखाएं',
    'dash.databaseSchema': 'डेटाबेस स्कीमा',
    'dash.flywayMigrations': 'फ्लाईवे माइग्रेशन',
    'dash.quickHub': 'त्वरित स्व-सेवा हब',
    'dash.applyLeaveDesc': 'वेतन सहित अवकाश या आकस्मिक अवकाश जमा करें',
    'dash.viewPayslipsDesc': 'मासिक वेतन विवरण और कर कटौती डाउनलोड करें',
    'dash.profileRequests': 'प्रोफ़ाइल अपडेट अनुरोध',
    'dash.profileRequestsDesc': 'पता, फ़ोन या बैंक विवरण अपडेट का अनुरोध करें',
    'dash.portalAccountId': 'पोर्टल खाता आईडी:',
    'dash.verificationStatus': 'सत्यापन स्थिति:',
    'dash.biometricLinked': 'सक्रिय • बायोमेट्रिक लिंक',

    // Requests Page
    'req.headerTitle': 'एचआर संचालन और अनुरोध डेस्क',
    'req.headerSubtitle': 'कर्मचारी प्रोफ़ाइल अपडेट स्वीकृतियों की समीक्षा करें और कर्मचारी एचआर पूछताछ का उत्तर दें।',
    'req.tabRequests': 'प्रोफ़ाइल परिवर्तन अनुरोध',
    'req.tabQueries': 'एचआर सहायता डेस्क और प्रश्न',
    'req.filterStatus': 'स्थिति:',
    'req.queryStatus': 'प्रश्न स्थिति:',
    'status.all': 'सभी',
    'status.pending': 'लंबित',
    'status.approved': 'स्वीकृत',
    'status.rejected': 'अस्वीकृत',
    'status.open': 'खुला',
    'status.inProgress': 'प्रगति में',
    'status.resolved': 'सुलझा हुआ',
    'status.closed': 'बंद',
    'req.thEmployee': 'कर्मचारी',
    'req.thChange': 'अनुरोधित परिवर्तन',
    'req.thCurrentVsRequested': 'वर्तमान बनाम अनुरोधित',
    'req.thStatus': 'स्थिति',
    'req.thSubmittedAt': 'जमा करने का समय',
    'req.thAction': 'समीक्षा कार्रवाई',
    'req.newRequest': 'नया परिवर्तन अनुरोध',
    'req.thEmpCode': 'कर्मचारी और कोड',
    'req.thSubjectCat': 'विषय और श्रेणी',
    'req.thAssignedHr': 'नियुक्त एचआर',
    'req.thPriority': 'प्राथमिकता',
    'req.actions': 'कार्रवाई',
    'req.reason': 'कारण:',
    'btn.approve': 'स्वीकृत करें',
    'btn.reject': 'अस्वीकार करें',
    'req.reviewedBy': 'द्वारा समीक्षित',
    'req.loadingRequests': 'अनुरोध लोड हो रहे हैं...',
    'req.noRequests': 'कोई प्रोफ़ाइल परिवर्तन अनुरोध नहीं मिला।',
    'req.loadingQueries': 'एचआर प्रश्न लोड हो रहे हैं...',
    'req.noQueries': 'कोई एचआर पूछताछ नहीं मिली।',
    'req.approveReq': 'परिवर्तन अनुरोध स्वीकृत करें',
    'req.rejectReq': 'परिवर्तन अनुरोध अस्वीकृत करें',
    'req.reviewerNotes': 'समीक्षक नोट्स (वैकल्पिक)',
    'req.confirmApprove': 'स्वीकृति की पुष्टि करें',
    'req.confirmReject': 'अस्वीकृति की पुष्टि करें',
    'req.submitChangeReq': 'प्रोफ़ाइल परिवर्तन अनुरोध जमा करें',
    'req.changeType': 'परिवर्तन प्रकार',
    'req.newRequestedVal': 'नया अनुरोधित मान',
    'req.reasonNote': 'कारण / सहायक नोट',
    'req.submitToHr': 'एचआर प्रबंधक को जमा करें',
    'req.hrQueryResponse': 'एचआर प्रश्न और समाधान',
    'req.hrReplyDetails': 'एचआर उत्तर और समाधान विवरण',
    'req.updateStatusTo': 'स्थिति अपडेट करें',
    'req.sendResolution': 'कर्मचारी को समाधान भेजें',
    'field.BANK_ACCOUNT': 'बैंक खाता और आईएफएससी',
    'field.CONTACT_NAME': 'कानूनी पूरा नाम',
    'field.EMAIL': 'आधिकारिक ईमेल',
    'field.OTHER': 'अन्य आधिकारिक रिकॉर्ड',
    'field.Bank Account Number': 'बैंक खाता संख्या',
    'field.Legal Full Name': 'कानूनी पूरा नाम',
    'field.Personal Email': 'व्यक्तिगत ईमेल',
    'field.Phone Number': 'फ़ोन नंबर',
    'field.Residential Address': 'आवासीय पता',

    // Modal
    'modal.onboardEmployee': 'नया कर्मचारी ऑनबोर्ड करें',
    'modal.firstName': 'पहला नाम',
    'modal.lastName': 'अंतिम नाम',
    'modal.workEmail': 'कार्य ईमेल',
    'modal.phone': 'फ़ोन नंबर',
    'modal.department': 'विभाग',
    'modal.selectDept': 'विभाग चुनें',
    'modal.employmentType': 'रोज़गार प्रकार',
    'modal.fullTime': 'पूर्णकालिक',
    'modal.partTime': 'अंशकालिक',
    'modal.contract': 'अनुबंध',
    'modal.joiningDate': 'शामिल होने की तिथि',
    'modal.cancel': 'रद्द करें',
    'modal.saveOnboard': 'सुरक्षित करें और ऑनबोर्ड करें',

    // Live Helpdesk Chat
    'chat.liveHelpdesk': 'लाइव एचआर सहायता डेस्क',
    'chat.online': 'ऑनलाइन',
    'chat.instantAssist': 'तत्काल कर्मचारी सहायता',
    'chat.connectedWith': 'एचआर विशेषज्ञ से जुड़े हुए हैं',
    'chat.startSupportChat': 'लाइव सहायता चैट शुरू करें',
    'chat.describeQuery': 'अपने प्रश्न या समस्या का वर्णन करें...',
    'chat.category': 'श्रेणी',
    'chat.generalQuery': 'सामान्य प्रश्न',
    'chat.payrollComp': 'वेतन और मुआवजा',
    'chat.leaveTimeOff': 'अवकाश और समय',
    'chat.pfBenefits': 'पीएफ और लाभ',
    'chat.profileDocs': 'प्रोफ़ाइल / दस्तावेज़',
    'chat.startSession': 'चैट सत्र शुरू करें',
    'chat.connecting': 'उपलब्ध एचआर विशेषज्ञ से जोड़ा जा रहा है...',
    'chat.send': 'भेजें',
    'chat.typeMessage': 'एचआर विशेषज्ञ को संदेश लिखें...',
    'chat.waitingInPool': 'उपलब्ध सहायता पूल में प्रतीक्षा कर रहे हैं...',
    'chat.resolveClose': 'समाधान करें और बंद करें',
    'chat.waitingForHr': 'एचआर विशेषज्ञ की प्रतीक्षा में...',
    'chat.queueNotice': 'आपका प्रश्न सहायता कतार में पहुंच गया है। उपलब्ध एचआर प्रशासक जल्द आपसे जुड़ेंगे।',
    'chat.employee': 'कर्मचारी',
    'chat.addDetailsPlaceholder': 'प्रतीक्षा के दौरान अतिरिक्त विवरण जोड़ें...',
    'chat.briefSubject': 'संक्षिप्त विषय',
    'chat.subjectPlaceholder': 'उदा. सितंबर वेतन पर्ची कटौती संबंधी प्रश्न',
    'chat.describeQueryLabel': 'अपने प्रश्न का वर्णन करें',
    'chat.describePlaceholder': 'विवरण लिखें ताकि एचआर प्रतिनिधि आपकी सहायता कर सके...',
    'chat.connectingPool': 'एचआर सहायता पूल से जोड़ा जा रहा है...',
    'chat.sendToAvailableHr': 'उपलब्ध एचआर को अनुरोध भेजें',
  },

  mr: {
    // Navigation & Sidebar
    'nav.coreModules': 'प्रमुख मॉड्यूल्स',
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.employees': 'कर्मचारी यादी',
    'nav.supportDesk': 'थेट सपोर्ट डेस्क',
    'nav.requests': 'विनंत्या आणि मंजुरी',
    'nav.attendance': 'हजेरी आणि रजा',
    'nav.payroll': 'पगार आणि भरपाई',
    'nav.organization': 'संस्था रचना',
    'nav.usersRoles': 'वापरकर्ते आणि भूमिका',
    'nav.auditLogs': 'ऑडिट आणि नियमपालन',
    'nav.more': 'अधिक',
    'sidebar.dbConnected': 'डेटाबेस कनेक्टेड',

    // Header & Profile Popover
    'header.searchPlaceholder': 'कर्मचारी, विनंती, नोंदी शोधा...',
    'header.companyName': 'प्रियॅक्स सॉफ्टवेअर एंटरप्राइज',
    'header.supportPool': 'मदत पूल',
    'header.notifications': 'सूचना',
    'header.myProfile': 'माझी प्रोफाइल',
    'header.systemRole': 'प्रणाली भूमिका',
    'header.accountId': 'खाते आयडी',
    'header.sessionStatus': 'सत्र स्थिती',
    'header.activeOnline': 'सक्रिय ऑनलाइन',
    'header.signOut': 'लॉग आऊट',
    'header.theme': 'थीम रंग',
    'header.language': 'भाषा निवडा',

    // Dashboard Banner & Headings
    'dash.welcomeBack': 'पुन्हा स्वागत आहे',
    'dash.enterprisePortal': 'एंटरप्राइज एचआर आणि कार्यबल पोर्टल',
    'dash.q3Overview': 'Q3 2026 एंटरप्राइज आढावा',
    'dash.adminSubtitle': 'सर्व सिस्टीम सुरळीत सुरू आहेत. पोस्टग्रेएसक्यूएल डेटाबेस सक्रिय आहे.',
    'dash.empSubtitle': 'तुमची प्रोफाइल तपासा, उपस्थिती कॅलेंडर पहा आणि रजेसाठी अर्ज करा.',
    'dash.applyLeave': 'रजेसाठी अर्ज करा',
    'dash.viewPayslips': 'पगार स्लिप पहा',
    'dash.addEmployee': 'नवीन कर्मचारी जोडा',
    'dash.downloadReport': 'अहवाल डाउनलोड करा',
    'dash.quickActions': 'जलद कृती',
    'dash.liveActivity': 'थेट प्रणाली घडामोडी',
    'dash.recentActivity': 'अलीकडील घडामोडी आणि टाइमलाइन',
    'dash.viewAll': 'सर्व पहा',

    // Activity Items
    'dash.act.onboarded': 'कर्मचारी नियुक्त',
    'dash.act.onboardedDesc': 'राजेश कुमार लीड फ्रंटएंड अभियंता म्हणून रुजू झाले',
    'dash.act.time10m': '१० मिनिटांपूर्वी',
    'dash.act.leaveApproved': 'रजा मंजूर',
    'dash.act.leaveApprovedDesc': 'प्रिया शर्मा - वार्षिक रजा (३ दिवस)',
    'dash.act.time25m': '२५ मिनिटांपूर्वी',
    'dash.act.payrollRun': 'पगार प्रक्रिया',
    'dash.act.payrollRunDesc': 'कर्मचाऱ्यांसाठी पगार मसुदा तयार',
    'dash.act.time1h': '१ तासापूर्वी',
    'dash.act.attendanceAlert': 'हजेरी चेतावणी',
    'dash.act.attendanceAlertDesc': 'पडताळणीसाठी ५ पंचआउट नोंदवले गेले नाहीत',
    'dash.act.time2h': '२ तासांपूर्वी',
    'dash.act.leaveRequest': 'रजा अर्ज',
    'dash.act.leaveRequestDesc': '२ ऑक्टोबरसाठी किरकोळ रजेचा अर्ज — मंजुरीची प्रतीक्षा',
    'dash.act.today': 'आज',
    'dash.act.attendanceRecorded': 'हजेरी नोंदवली',
    'dash.act.attendanceRecordedDesc': 'आज सकाळी ०९:१४ वाजता बायोमेट्रिक हजेरी — वेळेवर',
    'dash.act.payslipReleased': 'पगार स्लिप जारी',
    'dash.act.payslipReleasedDesc': 'ऑगस्ट २०२६ पगार पत्रक डाउनलोडसाठी तयार',
    'dash.act.yesterday': 'काल',
    'dash.act.hrSupport': 'एचआर मदत',
    'dash.act.hrSupportDesc': 'पीएफ आणि यूएएन प्रश्नाचे एचआर तज्ञाने उत्तर दिले',
    'dash.act.time2d': '२ दिवसांपूर्वी',

    // KPI Cards
    'dash.kpi.daysPresent': 'हजर दिवस',
    'dash.kpi.leaveBalance': 'शिल्लक रजा',
    'dash.kpi.latestNetPay': 'नवीनतम निव्वळ पगार',
    'dash.kpi.activeRequests': 'सक्रिय विनंत्या',
    'dash.kpi.totalStaff': 'एकूण कर्मचारी',
    'dash.kpi.presentToday': 'आज उपस्थित',
    'dash.kpi.staffOnLeave': 'रजेवर असलेले कर्मचारी',
    'dash.kpi.monthlyPayroll': 'मासिक पगार वितरण',
    'dash.kpi.onTime': '९५.५% वेळेवर हजेरी',
    'dash.kpi.daysAvailable': 'दिवस उपलब्ध',
    'dash.kpi.inReview': 'तपासणी सुरू',
    'dash.kpi.availableLeaves': '१४/१८ वार्षिक रजा शिल्लक',
    'dash.kpi.credited': '३१ ऑगस्ट रोजी जमा',
    'dash.kpi.awaitingApproval': 'मंजुरीची प्रतीक्षा',
    'dash.kpi.daysUnit': '/ २२ दिवस',
    'dash.kpi.perMonth': '/ महिना',
    'dash.kpi.activeStaff': 'सक्रिय कर्मचारी',
    'dash.kpi.staffTrend': 'मागील तिमाहीपेक्षा +१२%',
    'dash.kpi.staffRatio': 'कर्मचारी',
    'dash.kpi.dailyAttendance': 'दैनिक उपस्थिती',
    'dash.kpi.planned': 'नियोजित',
    'dash.kpi.leaveRate': 'दैनिक रजा दर',
    'dash.kpi.gross': 'एकूण',
    'dash.kpi.payrollTrend': '+४.२% वाढ',

    // Hub & Scope
    'dash.companyScope': 'कंपनी व्याप्ती',
    'dash.primaryEntity': 'मुख्य संस्था',
    'dash.activeBranches': 'सक्रिय शाखा',
    'dash.databaseSchema': 'डेटाबेस स्कीमा',
    'dash.flywayMigrations': 'मायग्रेशन नोंदी',
    'dash.quickHub': 'जलद स्व-सेवा केंद्र',
    'dash.applyLeaveDesc': 'पगारी किंवा किरकोळ रजेसाठी अर्ज करा',
    'dash.viewPayslipsDesc': 'मासिक पगार विवरणपत्र डाउनलोड करा',
    'dash.profileRequests': 'प्रोफाइल बदल विनंत्या',
    'dash.profileRequestsDesc': 'पत्ता, फोन किंवा बँक तपशील बदलासाठी विनंती करा',
    'dash.portalAccountId': 'पोर्टल खाते आयडी:',
    'dash.verificationStatus': 'सत्यापन स्थिती:',
    'dash.biometricLinked': 'सक्रिय • बायोमेट्रिक जोडलेले',

    // Requests Page
    'req.headerTitle': 'एचआर कार्ये आणि विनंती डेस्क',
    'req.headerSubtitle': 'कर्मचारी प्रोफाइल अपडेट मंजुरी तपासा आणि प्रश्नांची उत्तरे द्या.',
    'req.tabRequests': 'प्रोफाइल बदल विनंत्या',
    'req.tabQueries': 'एचआर मदत डेस्क आणि प्रश्न',
    'req.filterStatus': 'स्थिती:',
    'req.queryStatus': 'प्रश्न स्थिती:',
    'status.all': 'सर्व',
    'status.pending': 'प्रलंबित',
    'status.approved': 'मंजूर',
    'status.rejected': 'नाकारले',
    'status.open': 'उघडे',
    'status.inProgress': 'सुरू',
    'status.resolved': 'निकाली',
    'status.closed': 'बंद',
    'req.thEmployee': 'कर्मचारी',
    'req.thChange': 'बदल विनंती',
    'req.thCurrentVsRequested': 'सध्याचे विरूद्ध विनंती',
    'req.thStatus': 'स्थिती',
    'req.thSubmittedAt': 'सादर केलेली वेळ',
    'req.thAction': 'समीक्षा कृती',
    'req.newRequest': 'नवीन बदल अर्ज',
    'req.thEmpCode': 'कर्मचारी आणि कोड',
    'req.thSubjectCat': 'विषय आणि प्रवर्ग',
    'req.thAssignedHr': 'नियुक्त एचआर',
    'req.thPriority': 'प्राधान्य',
    'req.actions': 'कृती',
    'req.reason': 'कारण:',
    'btn.approve': 'मंजूर करा',
    'btn.reject': 'नाकारा',
    'req.reviewedBy': 'तपासणी केली',
    'req.loadingRequests': 'विनंत्या लोड होत आहेत...',
    'req.noRequests': 'कोणतीही विनंती आढळली नाही.',
    'req.loadingQueries': 'प्रश्न लोड होत आहेत...',
    'req.noQueries': 'कोणतीही विचारणा आढळली नाही.',
    'req.approveReq': 'विनंती मंजूर करा',
    'req.rejectReq': 'विनंती नाकारा',
    'req.reviewerNotes': 'पुनरावलोकन टिप्पणी (पर्यायी)',
    'req.confirmApprove': 'मंजुरीची खात्री करा',
    'req.confirmReject': 'नकाराची खात्री करा',
    'req.submitChangeReq': 'बदल विनंती अर्ज पाठवा',
    'req.changeType': 'बदल प्रकार',
    'req.newRequestedVal': 'नवीन मूल्य',
    'req.reasonNote': 'कारण / आधारभूत नोंद',
    'req.submitToHr': 'एचआर व्यवस्थापकास पाठवा',
    'req.hrQueryResponse': 'एचआर विचारणा व उत्तर',
    'req.hrReplyDetails': 'एचआर उत्तर व तोडगा तपशील',
    'req.updateStatusTo': 'स्थिती अपडेट करा',
    'req.sendResolution': 'कर्मचाऱ्यास तोडगा पाठवा',
    'field.BANK_ACCOUNT': 'बँक खाते व आयएफएससी',
    'field.CONTACT_NAME': 'कायदेशीर पूर्ण नाव',
    'field.EMAIL': 'अधिकृत ईमेल',
    'field.OTHER': 'इतर अधिकृत नोंद',
    'field.Bank Account Number': 'बँक खाते क्रमांक',
    'field.Legal Full Name': 'कायदेशीर पूर्ण नाव',
    'field.Personal Email': 'वैयक्तिक ईमेल',
    'field.Phone Number': 'फोन नंबर',
    'field.Residential Address': 'निवासी पत्ता',

    // Modal
    'modal.onboardEmployee': 'नवीन कर्मचारी ऑनबोर्ड करा',
    'modal.firstName': 'पहिले नाव',
    'modal.lastName': 'आडनाव',
    'modal.workEmail': 'कामकाज ईमेल',
    'modal.phone': 'फोन नंबर',
    'modal.department': 'विभाग',
    'modal.selectDept': 'विभाग निवडा',
    'modal.employmentType': 'रोजगार प्रकार',
    'modal.fullTime': 'पूर्णवेळ',
    'modal.partTime': 'अर्धवेळ',
    'modal.contract': 'कंत्राटी',
    'modal.joiningDate': 'सामील होण्याची तारीख',
    'modal.cancel': 'रद्द करा',
    'modal.saveOnboard': 'जतन करा आणि जोडा',

    // Live Helpdesk Chat
    'chat.liveHelpdesk': 'थेट एचआर मदत डेस्क',
    'chat.online': 'ऑनलाइन',
    'chat.instantAssist': 'त्वरित कर्मचारी मदत',
    'chat.connectedWith': 'एचआर तज्ञांशी जोडलेले',
    'chat.startSupportChat': 'थेट मदत चॅट सुरू करा',
    'chat.describeQuery': 'तुमची अडचण किंवा प्रश्न लिहा...',
    'chat.category': 'प्रवर्ग',
    'chat.generalQuery': 'सामान्य प्रश्न',
    'chat.payrollComp': 'पगार आणि भरपाई',
    'chat.leaveTimeOff': 'रजा आणि सुट्टी',
    'chat.pfBenefits': 'पीएफ आणि फायदे',
    'chat.profileDocs': 'प्रोफाइल / कागदपत्रे',
    'chat.startSession': 'चॅट सुरू करा',
    'chat.connecting': 'उपलब्ध एचआर तज्ञाशी जोडत आहे...',
    'chat.send': 'पाठवा',
    'chat.typeMessage': 'एचआर तज्ञांना संदेश लिहा...',
    'chat.waitingInPool': 'मदत पूलमध्ये वाट पाहत आहे...',
    'chat.resolveClose': 'निकाली काढा आणि बंद करा',
    'chat.waitingForHr': 'एचआर तज्ञाची प्रतीक्षा करत आहे...',
    'chat.queueNotice': 'तुमचा प्रश्न रांगेत जोडला गेला आहे. एचआर प्रशासक लवकरच जोडले जातील.',
    'chat.employee': 'कर्मचारी',
    'chat.addDetailsPlaceholder': 'तपशील लिहा...',
    'chat.briefSubject': 'संक्षिप्त विषय',
    'chat.subjectPlaceholder': 'उदा. सप्टेंबर पगार कपातीबाबत प्रश्न',
    'chat.describeQueryLabel': 'तुमच्या प्रश्नाचे वर्णन करा',
    'chat.describePlaceholder': 'एचआर प्रतिनिधीच्या मदतीसाठी तपशील लिहा...',
    'chat.connectingPool': 'एचआर पूलशी जोडत आहे...',
    'chat.sendToAvailableHr': 'उपलब्ध एचआरकडे विनंती पाठवा',
  },

  gu: {
    // Navigation & Sidebar
    'nav.coreModules': 'મુખ્ય મોડ્યુલ્સ',
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.employees': 'કર્મચારી યાદી',
    'nav.supportDesk': 'લાઇવ સપોર્ટ ડેસ્ક',
    'nav.requests': 'વિનંતીઓ અને મંજૂરી',
    'nav.attendance': 'હાજરી અને રજા',
    'nav.payroll': 'પગાર અને વળતર',
    'nav.organization': 'સંસ્થાનું માળખું',
    'nav.usersRoles': 'વપરાશકર્તાઓ અને ભૂમિકાઓ',
    'nav.auditLogs': 'ઓડિટ અને નિયમપાલન',
    'nav.more': 'વધુ',
    'sidebar.dbConnected': 'ડેટાબેઝ જોડાયેલ',

    // Header & Profile Popover
    'header.searchPlaceholder': 'ડિરેક્ટરી, વિનંતીઓ, રેકોર્ડ શોધો...',
    'header.companyName': 'પ્રિયેક્સ સોફ્ટવેર એન્ટરપ્રાઇઝ',
    'header.supportPool': 'સપોર્ટ પૂલ',
    'header.notifications': 'સૂચનાઓ',
    'header.myProfile': 'મારી પ્રોફાઇલ',
    'header.systemRole': 'સિસ્ટમ ભૂમિકા',
    'header.accountId': 'ખાતા આઈડી',
    'header.sessionStatus': 'સત્ર સ્થિતિ',
    'header.activeOnline': 'સક્રિય ઓનલાઇન',
    'header.signOut': 'લૉગ આઉટ કરો',
    'header.theme': 'થીમ રંગ',
    'header.language': 'ભાષા પસંદ કરો',

    // Dashboard Banner & Headings
    'dash.welcomeBack': 'સ્વાગત છે',
    'dash.enterprisePortal': 'એન્ટરપ્રાઇઝ એચઆર પોર્ટલ',
    'dash.q3Overview': 'Q3 2026 એન્ટરપ્રાઇઝ વિહંગાવલોકન',
    'dash.adminSubtitle': 'બધી સિસ્ટમો સામાન્ય છે. સુરક્ષિત ડેટાબેઝ સક્રિય છે.',
    'dash.empSubtitle': 'તમારી પ્રોફાઇલ જુઓ, હાજરી કેલેન્ડર તપાસો અને રજા માટે અરજી કરો.',
    'dash.applyLeave': 'રજા માટે અરજી કરો',
    'dash.viewPayslips': 'પગાર સ્લિપ જુઓ',
    'dash.addEmployee': 'કર્મચારી ઉમેરો',
    'dash.downloadReport': 'અહેવાલ ડાઉનલોડ કરો',
    'dash.quickActions': 'ઝડપી પગલાં',
    'dash.liveActivity': 'લાઇવ સિસ્ટમ પ્રવૃત્તિ',
    'dash.recentActivity': 'મારી તાજેતરની પ્રવૃત્તિ',
    'dash.viewAll': 'બધું જુઓ',

    // Activity Items
    'dash.act.onboarded': 'કર્મચારી જોડાયા',
    'dash.act.onboardedDesc': 'રાજેશ કુમાર લીડ ફ્રન્ટએન્ડ એન્જિનિયર તરીકે જોડાયા',
    'dash.act.time10m': '૧૦ મિનિટ પહેલાં',
    'dash.act.leaveApproved': 'રજા મંજૂર',
    'dash.act.leaveApprovedDesc': 'પ્રિયા શર્મા - વાર્ષિક રજા (૩ દિવસ)',
    'dash.act.time25m': '૨૫ મિનિટ પહેલાં',
    'dash.act.payrollRun': 'પગાર પ્રક્રિયા',
    'dash.act.payrollRunDesc': 'કર્મચારીઓ માટે પગાર ડ્રાફ્ટ તૈયાર',
    'dash.act.time1h': '૧ કલાક પહેલાં',
    'dash.act.attendanceAlert': 'હાજરી ચેતવણી',
    'dash.act.attendanceAlertDesc': 'ચકાસણી માટે ૫ મિસ્ડ પંચઆઉટ નોંધાયા',
    'dash.act.time2h': '૨ કલાક પહેલાં',
    'dash.act.leaveRequest': 'રજા વિનંતી',
    'dash.act.leaveRequestDesc': '૨ ઓક્ટોબર માટે રજા અરજી — મંજૂરીની રાહ જુએ છે',
    'dash.act.today': 'આજે',
    'dash.act.attendanceRecorded': 'હાજરી નોંધાઈ',
    'dash.act.attendanceRecordedDesc': 'આજે સવારે ૦૯:૧૪ વાગ્યે હાજરી — સમયસર',
    'dash.act.payslipReleased': 'પગાર સ્લિપ ઉપલબ્ધ',
    'dash.act.payslipReleasedDesc': 'ઓગસ્ટ ૨૦૨૬ પગાર પત્રક ડાઉનલોડ માટે તૈયાર',
    'dash.act.yesterday': 'ગઈકાલે',
    'dash.act.hrSupport': 'એચઆર સહાય',
    'dash.act.hrSupportDesc': 'પીએફ પ્રશ્નનો એચઆર દ્વારા ઉત્તર આપવામાં આવ્યો',
    'dash.act.time2d': '૨ દિવસ પહેલાં',

    // KPI Cards
    'dash.kpi.daysPresent': 'હાજર દિવસો',
    'dash.kpi.leaveBalance': 'બાકી રજાઓ',
    'dash.kpi.latestNetPay': 'ચોખ્ખો પગાર',
    'dash.kpi.activeRequests': 'સક્રિય વિનંતીઓ',
    'dash.kpi.totalStaff': 'કુલ કર્મચારીઓ',
    'dash.kpi.presentToday': 'આજે હાજર',
    'dash.kpi.staffOnLeave': 'રજા પર કર્મચારીઓ',
    'dash.kpi.monthlyPayroll': 'માસિક પગાર',
    'dash.kpi.onTime': '૯૫.૫% સમયસર હાજરી',
    'dash.kpi.daysAvailable': 'દિવસો ઉપલબ્ધ',
    'dash.kpi.inReview': 'સમીક્ષા હેઠળ',
    'dash.kpi.availableLeaves': '૧૪/૧૮ વાર્ષિક રજાઓ બાકી',
    'dash.kpi.credited': '૩૧ ઓગસ્ટે જમા',
    'dash.kpi.awaitingApproval': 'મંજૂરી બાકી',
    'dash.kpi.daysUnit': '/ ૨૨ દિવસ',
    'dash.kpi.perMonth': '/ માસ',
    'dash.kpi.activeStaff': 'સક્રિય સ્ટાફ',
    'dash.kpi.staffTrend': 'ગત ક્વાર્ટર કરતાં +૧૨%',
    'dash.kpi.staffRatio': 'સ્ટાફ',
    'dash.kpi.dailyAttendance': 'દૈનિક હાજરી',
    'dash.kpi.planned': 'આયોજિત',
    'dash.kpi.leaveRate': 'દૈનિક રજા દર',
    'dash.kpi.gross': 'કુલ',
    'dash.kpi.payrollTrend': '+૪.૨% વધારો',

    // Hub & Scope
    'dash.companyScope': 'કંપનીનો વ્યાપ',
    'dash.primaryEntity': 'મુખ્ય એકમ',
    'dash.activeBranches': 'સક્રિય શાખાઓ',
    'dash.databaseSchema': 'ડેટાબેઝ સ્કીમા',
    'dash.flywayMigrations': 'માઇગ્રેશન સ્થિતિ',
    'dash.quickHub': 'ઝડપી સ્વ-સેવા કેન્દ્ર',
    'dash.applyLeaveDesc': 'પગાર સાથેની કે આકસ્મિક રજા માટે અરજી કરો',
    'dash.viewPayslipsDesc': 'માસિક પગાર સ્લિપ અને ટેક્સ વિગત ડાઉનલોડ કરો',
    'dash.profileRequests': 'પ્રોફાઇલ સુધારણા વિનંતીઓ',
    'dash.profileRequestsDesc': 'સરનામું, ફોન અથવા બેંક વિગતો બદલવા અરજી કરો',
    'dash.portalAccountId': 'પોર્ટલ ખાતા આઈડી:',
    'dash.verificationStatus': 'ચકાસણી સ્થિતિ:',
    'dash.biometricLinked': 'સક્રિય • બાયોમેટ્રિક લિંક થયેલ',

    // Requests Page
    'req.headerTitle': 'એચઆર કામગીરી અને વિનંતી ડેસ્ક',
    'req.headerSubtitle': 'પ્રોફાઇલ અપડેટ મંજૂરીઓની સમીક્ષા કરો અને પ્રશ્નોના ઉત્તરો આપો.',
    'req.tabRequests': 'પ્રોફાઇલ સુધારણા વિનંતીઓ',
    'req.tabQueries': 'એચઆર સપોર્ટ ડેસ્ક અને પ્રશ્નો',
    'req.filterStatus': 'સ્થિતિ:',
    'req.queryStatus': 'પ્રશ્ન સ્થિતિ:',
    'status.all': 'બધા',
    'status.pending': 'બાકી',
    'status.approved': 'મંજૂર',
    'status.rejected': 'અસ્વીકાર',
    'status.open': 'ચાલુ',
    'status.inProgress': 'પ્રગતિમાં',
    'status.resolved': 'ઉકેલાયેલ',
    'status.closed': 'બંધ',
    'req.thEmployee': 'કર્મચારી',
    'req.thChange': 'સુધારાની વિનંતી',
    'req.thCurrentVsRequested': 'વર્તમાન વિરૂદ્ધ વિનંતી',
    'req.thStatus': 'સ્થિતિ',
    'req.thSubmittedAt': 'સબમિટ સમય',
    'req.thAction': 'સમીક્ષા કાર્યવાહી',
    'req.newRequest': 'નવી વિનંતી',
    'req.thEmpCode': 'કર્મચારી અને કોડ',
    'req.thSubjectCat': 'વિષય અને શ્રેણી',
    'req.thAssignedHr': 'સોંપેલ એચઆર',
    'req.thPriority': 'પ્રાથમિકતા',
    'req.actions': 'ક્રિયાઓ',
    'req.reason': 'કારણ:',
    'btn.approve': 'મંજૂર કરો',
    'btn.reject': 'અસ્વીકાર કરો',
    'req.reviewedBy': 'દ્વારા ચકાસાયેલ',
    'req.loadingRequests': 'વિનંતીઓ લોડ થઈ રહી છે...',
    'req.noRequests': 'કોઈ વિનંતી મળી નથી.',
    'req.loadingQueries': 'પ્રશ્નો લોડ થઈ રહ્યા છે...',
    'req.noQueries': 'કોઈ પ્રશ્નો મળ્યા નથી.',
    'req.approveReq': 'વિનંતી મંજૂર કરો',
    'req.rejectReq': 'વિનંતી અસ્વીકાર કરો',
    'req.reviewerNotes': 'સમીક્ષક નોંધ (વૈકલ્પિક)',
    'req.confirmApprove': 'મંજૂરીની ખાતરી કરો',
    'req.confirmReject': 'અસ્વીકારની ખાતરી કરો',
    'req.submitChangeReq': 'સુધારા વિનંતી સબમિટ કરો',
    'req.changeType': 'સુધારા પ્રકાર',
    'req.newRequestedVal': 'નવું મૂલ્ય',
    'req.reasonNote': 'કારણ / સહાયક નોંધ',
    'req.submitToHr': 'એચઆર મેનેજરને મોકલો',
    'req.hrQueryResponse': 'એચઆર પ્રશ્ન અને ઉકેલ',
    'req.hrReplyDetails': 'ઉકેલ વિગતો',
    'req.updateStatusTo': 'સ્થિતિ અપડેટ કરો',
    'req.sendResolution': 'કર્મચારીને ઉકેલ મોકલો',
    'field.BANK_ACCOUNT': 'બેંક ખાતું અને આઈએફએસસી',
    'field.CONTACT_NAME': 'કાયદેસર પૂરું નામ',
    'field.EMAIL': 'સત્તાવાર ઇમેઇલ',
    'field.OTHER': 'અન્ય રેકોર્ડ',
    'field.Bank Account Number': 'બેંક ખાતા નંબર',
    'field.Legal Full Name': 'કાયદેસર પૂરું નામ',
    'field.Personal Email': 'વ્યક્તિગત ઇમેઇલ',
    'field.Phone Number': 'ફોન નંબર',
    'field.Residential Address': 'રહેઠાણ સરનામું',

    // Modal
    'modal.onboardEmployee': 'નવા કર્મચારી ઉમેરો',
    'modal.firstName': 'પ્રથમ નામ',
    'modal.lastName': 'અટક',
    'modal.workEmail': 'કામકાજ ઇમેઇલ',
    'modal.phone': 'ફોન નંબર',
    'modal.department': 'વિભાગ',
    'modal.selectDept': 'વિભાગ પસંદ કરો',
    'modal.employmentType': 'રોજગાર પ્રકાર',
    'modal.fullTime': 'પૂર્ણ સમય',
    'modal.partTime': 'અંશકાલિક',
    'modal.contract': 'કરાર આધારિત',
    'modal.joiningDate': 'જોડાવાની તારીખ',
    'modal.cancel': 'રદ કરો',
    'modal.saveOnboard': 'સાચવો અને ઉમેરો',

    // Live Helpdesk Chat
    'chat.liveHelpdesk': 'લાઇવ એચઆર હેલ્પડેસ્ક',
    'chat.online': 'ઓનલાઇન',
    'chat.instantAssist': 'ત્વરિત કર્મચારી સહાય',
    'chat.connectedWith': 'એચઆર નિષ્ણાત સાથે જોડાયેલ',
    'chat.startSupportChat': 'લાઇવ સપોર્ટ ચેટ શરૂ કરો',
    'chat.describeQuery': 'તમારો પ્રશ્ન લખો...',
    'chat.category': 'શ્રેણી',
    'chat.generalQuery': 'સામાન્ય પ્રશ્ન',
    'chat.payrollComp': 'પગાર અને વળતર',
    'chat.leaveTimeOff': 'રજા અને સુવિધા',
    'chat.pfBenefits': 'પીએફ અને લાભો',
    'chat.profileDocs': 'પ્રોફાઇલ / દસ્તાવેજો',
    'chat.startSession': 'ચેટ શરૂ કરો',
    'chat.connecting': 'એચઆર નિષ્ણાત સાથે જોડી રહ્યા છીએ...',
    'chat.send': 'મોકલો',
    'chat.typeMessage': 'સંદેશ લખો...',
    'chat.waitingInPool': 'સહાય પૂલમાં રાહ જોઈ રહ્યા છીએ...',
    'chat.resolveClose': 'ઉકેલો અને બંધ કરો',
    'chat.waitingForHr': 'એચઆર પ્રતિનિધિની રાહ જુઓ...',
    'chat.queueNotice': 'તમારો પ્રશ્ન કતારમાં મૂકવામાં આવ્યો છે.',
    'chat.employee': 'કર્મચારી',
    'chat.addDetailsPlaceholder': 'વધારાની વિગત લખો...',
    'chat.briefSubject': 'સંક્ષિપ્ત વિષય',
    'chat.subjectPlaceholder': 'દા.ત., સપ્ટેમ્બર પગાર કપાત અંગે પ્રશ્ન',
    'chat.describeQueryLabel': 'તમારા પ્રશ્નનું વર્ણન કરો',
    'chat.describePlaceholder': 'વિગતો લખો જેથી પ્રતિનિધિ મદદ કરી શકે...',
    'chat.connectingPool': 'પૂલ સાથે જોડાઈ રહ્યા છીએ...',
    'chat.sendToAvailableHr': 'ઉપલબ્ધ એચઆરને વિનંતી મોકલો',
  },

  ta: {
    // Navigation & Sidebar
    'nav.coreModules': 'முக்கிய தொகுதிகள்',
    'nav.dashboard': 'முகப்பு பலகை',
    'nav.employees': 'பணியாளர்கள்',
    'nav.supportDesk': 'நேரலை உதவி மையம்',
    'nav.requests': 'கோரிக்கைகள் & ஒப்புதல்கள்',
    'nav.attendance': 'வருகை & விடுப்பு',
    'nav.payroll': 'ஊதியம் & சம்பளம்',
    'nav.organization': 'நிறுவன அமைப்பு',
    'nav.usersRoles': 'பயனர்கள் & பாத்திரங்கள்',
    'nav.auditLogs': 'தணிக்கை பதிவுகள்',
    'nav.more': 'மேலும்',
    'sidebar.dbConnected': 'தரவுத்தளம் இணைக்கப்பட்டது',

    // Header & Profile Popover
    'header.searchPlaceholder': 'தேடுக...',
    'header.companyName': 'பிரியெக்ஸ் மென்பொருள் நிறுவனம்',
    'header.supportPool': 'உதவி வரிசை',
    'header.notifications': 'அறிவிப்புகள்',
    'header.myProfile': 'என் சுயவிவரம்',
    'header.systemRole': 'கணினி பங்கு',
    'header.accountId': 'கணக்கு எண்',
    'header.sessionStatus': 'அமர்வு நிலை',
    'header.activeOnline': 'நேரலையில் உள்ளீர்கள்',
    'header.signOut': 'வெளியேறு',
    'header.theme': 'வண்ண தீம்',
    'header.language': 'மொழி தேர்வு',

    // Dashboard Banner & Headings
    'dash.welcomeBack': 'மீண்டும் வருக',
    'dash.enterprisePortal': 'நிறுவன மனிதவள தளம்',
    'dash.q3Overview': 'Q3 2026 நிறுவன கண்ணோட்டம்',
    'dash.adminSubtitle': 'அனைத்து அமைப்புகளும் சரியாக இயங்குகின்றன.',
    'dash.empSubtitle': 'உங்கள் வருகை மற்றும் விடுப்பு நிலையை எளிதாக சரிபார்க்கவும்.',
    'dash.applyLeave': 'விடுப்புக்கு விண்ணப்பிக்கவும்',
    'dash.viewPayslips': 'சம்பள சீட்டை பார்க்கவும்',
    'dash.addEmployee': 'புதிய பணியாளர் சேர்',
    'dash.downloadReport': 'அறிக்கை பதிவிறக்கு',
    'dash.quickActions': 'விரைவு நடவடிக்கைகள்',
    'dash.liveActivity': 'நேரலை நடவடிக்கைகள்',
    'dash.recentActivity': 'சமீபத்திய நடவடிக்கைகள்',
    'dash.viewAll': 'அனைத்தும் பார்க்க',

    // Activity Items
    'dash.act.onboarded': 'பணியாளர் சேர்ந்தார்',
    'dash.act.onboardedDesc': 'ராஜேஷ் குமார் முன்னிலை பொறியாளராக சேர்ந்தார்',
    'dash.act.time10m': '10 நிமிடங்களுக்கு முன்',
    'dash.act.leaveApproved': 'விடுப்பு ஒப்புதல் அளிக்கப்பட்டது',
    'dash.act.leaveApprovedDesc': 'பிரியா சர்மா - வருடாந்திர விடுப்பு (3 நாட்கள்)',
    'dash.act.time25m': '25 நிமிடங்களுக்கு முன்',
    'dash.act.payrollRun': 'சம்பள பட்டியல் தயாரிப்பு',
    'dash.act.payrollRunDesc': 'பணியாளர்களுக்கு சம்பளம் தயார்',
    'dash.act.time1h': '1 மணி நேரத்திற்கு முன்',
    'dash.act.attendanceAlert': 'வருகை எச்சரிக்கை',
    'dash.act.attendanceAlertDesc': '5 வருகை பதிவுகள் சரிபார்க்கப்பட வேண்டும்',
    'dash.act.time2h': '2 மணி நேரத்திற்கு முன்',
    'dash.act.leaveRequest': 'விடுப்பு கோரிக்கை',
    'dash.act.leaveRequestDesc': 'அக்டோபர் 2 க்கான தற்காலிக விடுப்பு கோரிக்கை — ஒப்புதலுக்கு காத்திருக்கிறது',
    'dash.act.today': 'இன்று',
    'dash.act.attendanceRecorded': 'வருகை பதிவு செய்யப்பட்டது',
    'dash.act.attendanceRecordedDesc': 'இன்று காலை 09:14 க்கு வருகை பதிவு — சரியான நேரம்',
    'dash.act.payslipReleased': 'சம்பள சீட்டு வெளியிடப்பட்டது',
    'dash.act.payslipReleasedDesc': 'ஆகஸ்ட் 2026 சம்பள சீட்டு தயார்',
    'dash.act.yesterday': 'நேற்று',
    'dash.act.hrSupport': 'உதவி பதில் அளிக்கப்பட்டது',
    'dash.act.hrSupportDesc': 'பி.எஃப் வினாவிற்கு நிபுணர் பதிலளித்தார்',
    'dash.act.time2d': '2 நாட்களுக்கு முன்',

    // KPI Cards
    'dash.kpi.daysPresent': 'வருகை நாட்கள்',
    'dash.kpi.leaveBalance': 'மீதமுள்ள விடுப்பு',
    'dash.kpi.latestNetPay': 'நிகர ஊதியம்',
    'dash.kpi.activeRequests': 'செயலில் உள்ள கோரிக்கைகள்',
    'dash.kpi.totalStaff': 'மொத்த ஊழியர்கள்',
    'dash.kpi.presentToday': 'இன்று வந்தவர்கள்',
    'dash.kpi.staffOnLeave': 'விடுப்பில் உள்ளவர்கள்',
    'dash.kpi.monthlyPayroll': 'மாத சம்பள பட்டியல்',
    'dash.kpi.onTime': '95.5% சரியான நேர வருகை',
    'dash.kpi.daysAvailable': 'நாட்கள் உள்ளன',
    'dash.kpi.inReview': 'பரிசீலனையில்',
    'dash.kpi.availableLeaves': '14/18 வருடாந்திர விடுப்பு மீதம்',
    'dash.kpi.credited': 'ஆகஸ்ட் 31 வரவு வைக்கப்பட்டது',
    'dash.kpi.awaitingApproval': 'ஒப்புதலுக்காக காத்திருக்கிறது',
    'dash.kpi.daysUnit': '/ 22 நாட்கள்',
    'dash.kpi.perMonth': '/ மாதம்',
    'dash.kpi.activeStaff': 'செயலில் உள்ள பணியாளர்கள்',
    'dash.kpi.staffTrend': '+12% வளர்ச்சி',
    'dash.kpi.staffRatio': 'பணியாளர்கள்',
    'dash.kpi.dailyAttendance': 'தினசரி வருகை',
    'dash.kpi.planned': 'திட்டமிட்டவை',
    'dash.kpi.leaveRate': 'தினசரி விடுப்பு வீதம்',
    'dash.kpi.gross': 'மொத்தம்',
    'dash.kpi.payrollTrend': '+4.2% பட்டுவாடா',

    // Hub & Scope
    'dash.companyScope': 'நிறுவன நோக்கம்',
    'dash.primaryEntity': 'முதன்மை நிறுவனம்',
    'dash.activeBranches': 'செயலில் உள்ள கிளைகள்',
    'dash.databaseSchema': 'தரவுத்தள அமைப்பு',
    'dash.flywayMigrations': 'நிலை பதிவுகள்',
    'dash.quickHub': 'விரைவு சுயசேவை மையம்',
    'dash.applyLeaveDesc': 'விடுப்பு அல்லது அனுமதிக்கு விண்ணப்பிக்கவும்',
    'dash.viewPayslipsDesc': 'மாதாந்திர சம்பள விவரங்களை பதிவிறக்கவும்',
    'dash.profileRequests': 'சுயவிவர புதுப்பிப்பு கோரிக்கைகள்',
    'dash.profileRequestsDesc': 'முகவரி, தொலைபேசி அல்லது வங்கி விவரங்களை மாற்றவும்',
    'dash.portalAccountId': 'கணக்கு ஐடி:',
    'dash.verificationStatus': 'சரிபார்ப்பு நிலை:',
    'dash.biometricLinked': 'செயலில் • பயோமெட்ரிக் இணைக்கப்பட்டுள்ளது',

    // Requests Page
    'req.headerTitle': 'மனிதவள மேலாண்மை & கோரிக்கை பலகை',
    'req.headerSubtitle': 'சுயவிவர மாற்ற கோரிக்கைகளை பரிசீலித்து ஒப்புதல் அளிக்கவும்.',
    'req.tabRequests': 'சுயவிவர மாற்ற கோரிக்கைகள்',
    'req.tabQueries': 'உதவி மையம் & கேள்விகள்',
    'req.filterStatus': 'நிலை:',
    'status.all': 'அனைத்தும்',
    'status.pending': 'நிலுவையில்',
    'status.approved': 'ஏற்கப்பட்டது',
    'status.rejected': 'நிராகரிக்கப்பட்டது',
    'status.open': 'திறந்தது',
    'status.inProgress': 'செயலில்',
    'status.resolved': 'தீர்வு காணப்பட்டது',
    'status.closed': 'மூடப்பட்டது',
    'req.thEmployee': 'பணியாளர்',
    'req.thChange': 'கோரப்பட்ட மாற்றம்',
    'req.thCurrentVsRequested': 'தற்போதைய vs கோரப்பட்ட',
    'req.thStatus': 'நிலை',
    'req.thSubmittedAt': 'சமர்ப்பிக்கப்பட்ட நேரம்',
    'req.thAction': 'நடவடிக்கை',
    'req.newRequest': 'புதிய கோரிக்கை',

    // Modal
    'modal.onboardEmployee': 'புதிய பணியாளர் பதிவு',
    'modal.firstName': 'முதல் பெயர்',
    'modal.lastName': 'கடைசி பெயர்',
    'modal.workEmail': 'அலுவலக மின்னஞ்சல்',
    'modal.phone': 'தொலைபேசி எண்',
    'modal.department': 'துறை',
    'modal.selectDept': 'துறையை தேர்வு செய்க',
    'modal.employmentType': 'பணி வகை',
    'modal.fullTime': 'முழு நேரம்',
    'modal.partTime': 'பகுதி நேரம்',
    'modal.contract': 'ஒப்பந்தம்',
    'modal.joiningDate': 'சேர்ந்த தேதி',
    'modal.cancel': 'ரத்து செய்',
    'modal.saveOnboard': 'சேமி & பணியமர்த்து',

    // Live Helpdesk Chat
    'chat.liveHelpdesk': 'நேரலை உதவி மையம்',
    'chat.online': 'இணைப்பில் உள்ளது',
    'chat.connectedWith': 'நிபுணருடன் இணைக்கப்பட்டுள்ளீர்கள்',
    'chat.startSupportChat': 'நேரலை உரையாடலை தொடங்கவும்',
    'chat.describeQuery': 'உங்கள் கேள்வியை விளக்குங்கள்...',
    'chat.category': 'வகை',
    'chat.generalQuery': 'பொதுவான கேள்வி',
    'chat.payrollComp': 'ஊதியம் & சம்பளம்',
    'chat.leaveTimeOff': 'விடுப்பு & நேரம்',
    'chat.pfBenefits': 'பி.எஃப் & பயன்கள்',
    'chat.profileDocs': 'சுயவிவரம் / ஆவணங்கள்',
    'chat.startSession': 'உரையாடலை தொடங்கு',
    'chat.connecting': 'இணைக்கப்படுகிறது...',
    'chat.send': 'அனுப்பு',
    'chat.typeMessage': 'செய்தியை தட்டச்சு செய்யவும்...',
    'chat.waitingInPool': 'உதவி வரிசையில் காத்திருக்கிறது...',
    'chat.resolveClose': 'தீர்வு & மூடு',
    'chat.waitingForHr': 'நிபுணருக்காக காத்திருக்கிறது...',
    'chat.queueNotice': 'உங்கள் கேள்வி பதிவு செய்யப்பட்டது.',
    'chat.employee': 'பணியாளர்',
    'chat.addDetailsPlaceholder': 'கூடுதல் தகவல்களை எழுதவும்...',
  },

  te: {
    // Navigation & Sidebar
    'nav.coreModules': 'ప్రధాన మాడ్యూల్స్',
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.employees': 'ఉద్యోగులు',
    'nav.supportDesk': 'లైవ్ సపోర్ట్ డెస్క్',
    'nav.requests': 'అభ్యర్థనలు & ఆమోదాలు',
    'nav.attendance': 'హాజరు & సెలవులు',
    'nav.payroll': 'జీతం & పరిహారం',
    'nav.organization': 'సంస్థ నిర్మాణం',
    'nav.usersRoles': 'వినియోగదారులు & పాత్రలు',
    'nav.auditLogs': 'ఆడిట్ లాగ్స్',
    'nav.more': 'మరిన్ని',
    'sidebar.dbConnected': 'డేటాబేస్ అనుసంధానించబడింది',

    // Header & Profile Popover
    'header.searchPlaceholder': 'శోధించండి...',
    'header.companyName': 'ప్రియెక్స్ సాఫ్ట్‌వేర్ ఎంటర్‌ప్రైజ్',
    'header.supportPool': 'సహాయ పూల్',
    'header.notifications': 'నోటిఫికేషన్లు',
    'header.myProfile': 'నా ప్రొఫైల్',
    'header.systemRole': 'సిస్టమ్ పాత్ర',
    'header.accountId': 'ఖాతా ఐడీ',
    'header.sessionStatus': 'సెషన్ స్థితి',
    'header.activeOnline': 'ఆన్‌లైన్‌లో ఉన్నారు',
    'header.signOut': 'లాగ్ అవుట్',
    'header.theme': 'థీమ్ రంగు',
    'header.language': 'భాష ఎంచుకోండి',

    // Dashboard Banner & Headings
    'dash.welcomeBack': 'స్వాగతం',
    'dash.enterprisePortal': 'ఎంటర్‌ప్రైజ్ హెచ్ఆర్ పోర్టల్',
    'dash.q3Overview': 'Q3 2026 సంస్థ పరిశీలన',
    'dash.adminSubtitle': 'అన్ని సిస్టమ్‌లు సాధారణంగా పనిచేస్తున్నాయి.',
    'dash.empSubtitle': 'మీ ప్రొఫైల్, హాజరు క్యాలెండర్ చూసి సెలవుల కోసం దరఖాస్తు చేసుకోండి.',
    'dash.applyLeave': 'సెలవు కోసం దరఖాస్తు చేసుకోండి',
    'dash.viewPayslips': 'పేస్లిప్‌లను చూడండి',
    'dash.addEmployee': 'ఉద్యోగిని జోడించండి',
    'dash.downloadReport': 'నివేదికను డౌన్‌లోడ్ చేయండి',
    'dash.quickActions': 'శీఘ్ర చర్యలు',
    'dash.liveActivity': 'లైవ్ కార్యకలాపాలు',
    'dash.recentActivity': 'ఇటీవలి కార్యాచరణ & కాలక్రమం',
    'dash.viewAll': 'అన్నీ చూడండి',

    // Activity Items
    'dash.act.onboarded': 'ఉద్యోగి చేరారు',
    'dash.act.onboardedDesc': 'రాజేష్ కుమార్ లీడ్ ఇంజనీర్‌గా చేరారు',
    'dash.act.time10m': '10 నిమిషాల క్రితం',
    'dash.act.leaveApproved': 'సెలవు ఆమోదించబడింది',
    'dash.act.leaveApprovedDesc': 'ప్రియా శర్మ - వార్షిక సెలవు (3 రోజులు)',
    'dash.act.time25m': '25 నిమిషాల క్రితం',
    'dash.act.payrollRun': 'పేరోల్ ప్రక్రియ',
    'dash.act.payrollRunDesc': 'ఉద్యోగులకు పేరోల్ ముసాయిదా సిద్ధం',
    'dash.act.time1h': '1 గంట క్రితం',
    'dash.act.attendanceAlert': 'హాజరు హెచ్చరిక',
    'dash.act.attendanceAlertDesc': 'ధృవీకరణ కోసం 5 పంచ్‌లు గుర్తించబడ్డాయి',
    'dash.act.time2h': '2 గంటల క్రితం',
    'dash.act.leaveRequest': 'సెలవు అభ్యర్థన',
    'dash.act.leaveRequestDesc': 'అక్టోబర్ 2 సెలవు అభ్యర్థన — ఆమోదం కోసం వేచి ఉంది',
    'dash.act.today': 'ఈ రోజు',
    'dash.act.attendanceRecorded': 'హాజరు నమోదు అయింది',
    'dash.act.attendanceRecordedDesc': 'ఉదయం 09:14 గంటలకు హాజరు నమోదు — సమయానికి',
    'dash.act.payslipReleased': 'పేస్లిప్ విడుదలైంది',
    'dash.act.payslipReleasedDesc': 'ఆగస్టు 2026 పేస్లిప్ సిద్ధంగా ఉంది',
    'dash.act.yesterday': 'నిన్న',
    'dash.act.hrSupport': 'హెచ్ఆర్ మద్దతు',
    'dash.act.hrSupportDesc': 'పీఎఫ్ ప్రశ్నకు నిపుణుల సమాధానం',
    'dash.act.time2d': '2 రోజుల క్రితం',

    // KPI Cards
    'dash.kpi.daysPresent': 'హాజరైన రోజులు',
    'dash.kpi.leaveBalance': 'సెలవుల నిల్వ',
    'dash.kpi.latestNetPay': 'నికర జీతం',
    'dash.kpi.activeRequests': 'క్రియాశీల అభ్యర్థనలు',
    'dash.kpi.totalStaff': 'మొత్తం ఉద్యోగులు',
    'dash.kpi.presentToday': 'ఈరోజు హాజరైనవారు',
    'dash.kpi.staffOnLeave': 'సెలవులో ఉన్నవారు',
    'dash.kpi.monthlyPayroll': 'నెలవారీ పేరోల్',
    'dash.kpi.onTime': '95.5% సరైన సమయానికి హాజరు',
    'dash.kpi.daysAvailable': 'రోజులు అందుబాటులో ఉన్నాయి',
    'dash.kpi.inReview': 'సమీక్షలో ఉంది',
    'dash.kpi.availableLeaves': '14/18 వార్షిక సెలవులు మిగిలి ఉన్నాయి',
    'dash.kpi.credited': 'ఆగస్టు 31న జమ చేయబడింది',
    'dash.kpi.awaitingApproval': 'ఆమోదం కోసం వేచి ఉంది',
    'dash.kpi.daysUnit': '/ 22 రోజులు',
    'dash.kpi.perMonth': '/ నెల',
    'dash.kpi.activeStaff': 'యాక్టివ్ సిబ్బంది',
    'dash.kpi.staffTrend': 'గత త్రైమాసికం కంటే +12%',
    'dash.kpi.staffRatio': 'సిబ్బంది',
    'dash.kpi.dailyAttendance': 'రోజువారీ హాజరు',
    'dash.kpi.planned': 'ప్రణాళిక ప్రకారం',
    'dash.kpi.leaveRate': 'రోజువారీ సెలవు రేటు',
    'dash.kpi.gross': 'మొత్తం',
    'dash.kpi.payrollTrend': '+4.2% పంపిణీ',

    // Hub & Scope
    'dash.companyScope': 'సంస్థ పరిధి',
    'dash.primaryEntity': 'ప్రధాన సంస్థ',
    'dash.activeBranches': 'యాక్టివ్ శాఖలు',
    'dash.databaseSchema': 'డేటాబేస్ స్కీమా',
    'dash.flywayMigrations': 'మైగ్రేషన్స్',
    'dash.quickHub': 'శీఘ్ర స్వీయ-సేవా కేంద్రం',
    'dash.applyLeaveDesc': 'సెలవు లేదా అత్యవసర సెలవు కోసం దరఖాస్తు చేసుకోండి',
    'dash.viewPayslipsDesc': 'నెలవారీ జీతం స్లిప్ డౌన్‌లోడ్ చేయండి',
    'dash.profileRequests': 'ప్రొఫైల్ అప్‌డేట్ అభ్యర్థనలు',
    'dash.profileRequestsDesc': 'చిరునామా, ఫోన్ లేదా బ్యాంక్ వివరాలను మార్చండి',
    'dash.portalAccountId': 'ఖాతా ఐడీ:',
    'dash.verificationStatus': 'ధృవీకరణ స్థితి:',
    'dash.biometricLinked': 'క్రియాశీలం • బయోమెట్రిక్ లింక్ అయింది',

    // Requests Page
    'req.headerTitle': 'హెచ్ఆర్ కార్యకలాపాలు & అభ్యర్థన డెస్క్',
    'req.headerSubtitle': 'ప్రొఫైల్ మార్పుల అభ్యర్థనలను సమీక్షించండి మరియు ఆమోదించండి.',
    'req.tabRequests': 'ప్రొఫైల్ మార్పు అభ్యర్థనలు',
    'req.tabQueries': 'సహాయ డెస్క్ & ప్రశ్నలు',
    'req.filterStatus': 'స్థితి:',
    'status.all': 'అన్నీ',
    'status.pending': 'పెండింగ్',
    'status.approved': 'ఆమోదించబడింది',
    'status.rejected': 'తిరస్కరించబడింది',
    'status.open': 'ఓపెన్',
    'status.inProgress': 'పురోగతిలో ఉంది',
    'status.resolved': 'పరిష్కరించబడింది',
    'status.closed': 'ముగిసింది',
    'req.thEmployee': 'ఉద్యోగి',
    'req.thChange': 'అభ్యర్థించిన మార్పు',
    'req.thCurrentVsRequested': 'ప్రస్తుత vs అభ్యర్థించిన',
    'req.thStatus': 'స్థితి',
    'req.thSubmittedAt': 'సమర్పించిన సమయం',
    'req.thAction': 'చర్య',
    'req.newRequest': 'కొత్త మార్పు అభ్యర్థన',

    // Modal
    'modal.onboardEmployee': 'కొత్త ఉద్యోగిని చేర్చండి',
    'modal.firstName': 'మొదటి పేరు',
    'modal.lastName': 'చివరి పేరు',
    'modal.workEmail': 'కార్యాలయ ఇమెయిల్',
    'modal.phone': 'ఫోన్ నంబర్',
    'modal.department': 'విభాగం',
    'modal.selectDept': 'విభాగాన్ని ఎంచుకోండి',
    'modal.employmentType': 'ఉద్యోగ రకం',
    'modal.fullTime': 'పూర్తి సమయం',
    'modal.partTime': 'పార్ట్ టైమ్',
    'modal.contract': 'కాంట్రాక్ట్',
    'modal.joiningDate': 'చేరిన తేదీ',
    'modal.cancel': 'రద్దు చేయి',
    'modal.saveOnboard': 'సేవ్ & చేర్చండి',

    // Live Helpdesk Chat
    'chat.liveHelpdesk': 'లైవ్ హెచ్ఆర్ హెల్ప్‌డెస్క్',
    'chat.online': 'ఆన్‌లైన్',
    'chat.connectedWith': 'హెచ్ఆర్ స్పెషలిస్ట్‌తో కనెక్ట్ అయ్యారు',
    'chat.startSupportChat': 'లైవ్ చాట్ ప్రారంభించండి',
    'chat.describeQuery': 'మీ ప్రశ్నను వివరించండి...',
    'chat.category': 'వర్గం',
    'chat.generalQuery': 'సాధారణ ప్రశ్న',
    'chat.payrollComp': 'జీతం & పరిహారం',
    'chat.leaveTimeOff': 'సెలవులు & సమయం',
    'chat.pfBenefits': 'పీఎఫ్ & ప్రయోజనాలు',
    'chat.profileDocs': 'ప్రొఫైల్ / పత్రాలు',
    'chat.startSession': 'చాట్ ప్రారంభించండి',
    'chat.connecting': 'కనెక్ట్ చేస్తోంది...',
    'chat.send': 'పంపు',
    'chat.typeMessage': 'సందేశం రాయండి...',
    'chat.waitingInPool': 'సహాయ పూల్‌లో వేచి ఉన్నారు...',
    'chat.resolveClose': 'పరిష్కరించి మూసివేయండి',
    'chat.waitingForHr': 'హెచ్ఆర్ నిపుణుడి కోసం వేచి ఉంది...',
    'chat.queueNotice': 'మీ అభ్యర్థన క్యూలోకి చేరింది.',
    'chat.employee': 'ఉద్యోగి',
    'chat.addDetailsPlaceholder': 'వివరాలు జోడించండి...',
  },

  es: {
    // Navigation & Sidebar
    'nav.coreModules': 'Módulos Principales',
    'nav.dashboard': 'Panel de Control',
    'nav.employees': 'Empleados',
    'nav.supportDesk': 'Mesa de Ayuda en Vivo',
    'nav.requests': 'Solicitudes y Aprobaciones',
    'nav.attendance': 'Asistencia y Permisos',
    'nav.payroll': 'Nómina y Salarios',
    'nav.organization': 'Organización',
    'nav.usersRoles': 'Usuarios y Roles',
    'nav.auditLogs': 'Auditoría y Cumplimiento',
    'nav.more': 'Más',
    'sidebar.dbConnected': 'Base de Datos Conectada',

    // Header & Profile Popover
    'header.searchPlaceholder': 'Buscar en directorio, registros...',
    'header.companyName': 'Priyex Software Enterprise',
    'header.supportPool': 'Cola',
    'header.notifications': 'Notificaciones',
    'header.myProfile': 'Mi Perfil',
    'header.systemRole': 'Rol del Sistema',
    'header.accountId': 'ID de Cuenta',
    'header.sessionStatus': 'Estado de Sesión',
    'header.activeOnline': 'En línea',
    'header.signOut': 'Cerrar Sesión',
    'header.theme': 'Color del Tema',
    'header.language': 'Seleccionar Idioma',

    // Dashboard Banner & Headings
    'dash.welcomeBack': 'Bienvenido de nuevo',
    'dash.enterprisePortal': 'Portal Empresarial de Gestión Humana',
    'dash.q3Overview': 'Resumen Empresarial Q3 2026',
    'dash.adminSubtitle': 'Todos los sistemas funcionan con normalidad. Base de datos PostgreSQL aislada y activa.',
    'dash.empSubtitle': 'Acceda a su perfil de empleado, calendario de turnos y solicite permisos.',
    'dash.applyLeave': 'Solicitar Permiso',
    'dash.viewPayslips': 'Ver Recibos de Pago',
    'dash.addEmployee': 'Añadir Empleado',
    'dash.downloadReport': 'Descargar Informe',
    'dash.quickActions': 'Acciones Rápidas',
    'dash.liveActivity': 'Actividad del Sistema en Vivo',
    'dash.recentActivity': 'Mi Actividad y Cronograma Reciente',
    'dash.viewAll': 'Ver Todo',

    // Activity Items
    'dash.act.onboarded': 'Empleado Incorporado',
    'dash.act.onboardedDesc': 'Rajesh Kumar se unió como Ingeniero Frontend Principal',
    'dash.act.time10m': 'Hace 10 mins',
    'dash.act.leaveApproved': 'Permiso Aprobado',
    'dash.act.leaveApprovedDesc': 'Priya Sharma - Vacaciones Anuales (3 días)',
    'dash.act.time25m': 'Hace 25 mins',
    'dash.act.payrollRun': 'Ejecución de Nómina',
    'dash.act.payrollRunDesc': 'Borrador de nómina generado para empleados activos',
    'dash.act.time1h': 'Hace 1 hora',
    'dash.act.attendanceAlert': 'Alerta de Asistencia',
    'dash.act.attendanceAlertDesc': '5 registros pendientes de verificación',
    'dash.act.time2h': 'Hace 2 horas',
    'dash.act.leaveRequest': 'Solicitud de Permiso',
    'dash.act.leaveRequestDesc': 'Solicitud de permiso para el 2 de oct — Pendiente de aprobación',
    'dash.act.today': 'Hoy',
    'dash.act.attendanceRecorded': 'Asistencia Registrada',
    'dash.act.attendanceRecordedDesc': 'Entrada biométrica registrada a las 09:14 AM — A tiempo',
    'dash.act.payslipReleased': 'Recibo Emitido',
    'dash.act.payslipReleasedDesc': 'Recibo de agosto 2026 disponible para descarga',
    'dash.act.yesterday': 'Ayer',
    'dash.act.hrSupport': 'Soporte RRHH',
    'dash.act.hrSupportDesc': 'Consulta respondida por el especialista',
    'dash.act.time2d': 'Hace 2 días',

    // KPI Cards
    'dash.kpi.daysPresent': 'Días Presente',
    'dash.kpi.leaveBalance': 'Saldo de Permisos',
    'dash.kpi.latestNetPay': 'Último Salario Neto',
    'dash.kpi.activeRequests': 'Solicitudes Activas',
    'dash.kpi.totalStaff': 'Personal Total',
    'dash.kpi.presentToday': 'Presentes Hoy',
    'dash.kpi.staffOnLeave': 'Personal de Permiso',
    'dash.kpi.monthlyPayroll': 'Nómina Mensual',
    'dash.kpi.onTime': '95.5% asistencia a tiempo',
    'dash.kpi.daysAvailable': 'Días Disponibles',
    'dash.kpi.inReview': 'En Revisión',
    'dash.kpi.availableLeaves': '14 de 18 días restantes',
    'dash.kpi.credited': 'Acreditado el 31 de agosto',
    'dash.kpi.awaitingApproval': 'Pendiente de aprobación',
    'dash.kpi.daysUnit': '/ 22 días',
    'dash.kpi.perMonth': '/ mes',
    'dash.kpi.activeStaff': 'Personal Activo',
    'dash.kpi.staffTrend': '+12% vs trimestre anterior',
    'dash.kpi.staffRatio': 'empleados',
    'dash.kpi.dailyAttendance': 'asistencia diaria',
    'dash.kpi.planned': 'Planificado',
    'dash.kpi.leaveRate': 'tasa diaria de permisos',
    'dash.kpi.gross': 'Bruto',
    'dash.kpi.payrollTrend': '+4.2% desembolsado',

    // Hub & Scope
    'dash.companyScope': 'Alcance Corporativo',
    'dash.primaryEntity': 'Entidad Principal',
    'dash.activeBranches': 'Sucursales Activas',
    'dash.databaseSchema': 'Esquema de Base de Datos',
    'dash.flywayMigrations': 'Migraciones Flyway',
    'dash.quickHub': 'Centro Rápido de Autoservicio',
    'dash.applyLeaveDesc': 'Solicite vacaciones o permisos retribuidos',
    'dash.viewPayslipsDesc': 'Descargue el desglose de nómina e impuestos',
    'dash.profileRequests': 'Solicitudes de Perfil',
    'dash.profileRequestsDesc': 'Solicite actualización de dirección, teléfono o banco',
    'dash.portalAccountId': 'ID de Cuenta del Portal:',
    'dash.verificationStatus': 'Estado de Verificación:',
    'dash.biometricLinked': 'Activo • Biometría Vinculada',

    // Requests Page
    'req.headerTitle': 'Mesa de Operaciones y Solicitudes de RRHH',
    'req.headerSubtitle': 'Revise las aprobaciones de actualización y responda consultas.',
    'req.tabRequests': 'Solicitudes de Cambio de Perfil',
    'req.tabQueries': 'Mesa de Ayuda y Consultas',
    'req.filterStatus': 'Estado:',
    'status.all': 'TODOS',
    'status.pending': 'PENDIENTE',
    'status.approved': 'APROBADO',
    'status.rejected': 'RECHAZADO',
    'status.open': 'ABIERTO',
    'status.inProgress': 'EN PROCESO',
    'status.resolved': 'RESUELTO',
    'status.closed': 'CERRADO',
    'req.thEmployee': 'Empleado',
    'req.thChange': 'Cambio Solicitado',
    'req.thCurrentVsRequested': 'Actual vs Solicitado',
    'req.thStatus': 'Estado',
    'req.thSubmittedAt': 'Fecha de Envío',
    'req.thAction': 'Acción de Revisión',
    'req.newRequest': 'Nueva Solicitud',

    // Modal
    'modal.onboardEmployee': 'Incorporar Nuevo Empleado',
    'modal.firstName': 'Nombre',
    'modal.lastName': 'Apellidos',
    'modal.workEmail': 'Correo Laboral',
    'modal.phone': 'Teléfono Personal',
    'modal.department': 'Departamento',
    'modal.selectDept': 'Seleccionar Departamento',
    'modal.employmentType': 'Tipo de Contrato',
    'modal.fullTime': 'Tiempo Completo',
    'modal.partTime': 'Tiempo Parcial',
    'modal.contract': 'Por Contrato',
    'modal.joiningDate': 'Fecha de Ingreso',
    'modal.cancel': 'Cancelar',
    'modal.saveOnboard': 'Guardar e Incorporar',

    // Live Helpdesk Chat
    'chat.liveHelpdesk': 'Mesa de Ayuda RRHH en Vivo',
    'chat.online': 'En Línea',
    'chat.connectedWith': 'Conectado con Especialista de RRHH',
    'chat.startSupportChat': 'Iniciar Chat de Soporte',
    'chat.describeQuery': 'Describa su consulta o pregunta...',
    'chat.category': 'Categoría',
    'chat.generalQuery': 'Consulta General',
    'chat.payrollComp': 'Nómina y Salarios',
    'chat.leaveTimeOff': 'Vacaciones y Permisos',
    'chat.pfBenefits': 'Beneficios y Retenciones',
    'chat.profileDocs': 'Perfil / Documentos',
    'chat.startSession': 'Iniciar Sesión de Chat',
    'chat.connecting': 'Conectando con un especialista...',
    'chat.send': 'Enviar',
    'chat.typeMessage': 'Escriba un mensaje al especialista...',
    'chat.waitingInPool': 'Esperando en la cola de asignación...',
    'chat.resolveClose': 'Resolver y Cerrar',
    'chat.waitingForHr': 'Esperando a un especialista de RRHH...',
    'chat.queueNotice': 'Su consulta ha ingresado a la cola. Un administrador se conectará pronto.',
    'chat.employee': 'Empleado',
    'chat.addDetailsPlaceholder': 'Añada más detalles mientras espera...',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  currentLanguageOption: LanguageOption;
  availableLanguages: LanguageOption[];
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('priyex_hrms_lang') as LanguageCode;
    return saved && TRANSLATIONS[saved] ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('priyex_hrms_lang', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
  };

  const t = (key: string, fallback?: string): string => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (langDict[key]) {
      return langDict[key];
    }
    // Fallback to English dictionary
    if (TRANSLATIONS.en[key]) {
      return TRANSLATIONS.en[key];
    }
    return fallback || key;
  };

  const currentLanguageOption =
    SUPPORTED_LANGUAGES.find((l) => l.code === language) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        currentLanguageOption,
        availableLanguages: SUPPORTED_LANGUAGES,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
